// export const initialData = [
//     "Elizabee",
//     "Jolthog Cryst",
//     "Nox",
//     "Mau",
//     "Mozzarina",
//     "Gobfin Ignis",
//     "Hangyu Cryst",
//     "Mossanda Lux",
//     "Woolipop",
//     "Incineram",
//     "Leezpunk",
//     "Leezpunk Ignis",
//     "Loupmoon",
//     "Grintale",
//     "Chillet Ignis",
//     "Foxcicle",
//     "Pyrin",
//     "Pyrin Noct",
//     "Kitsun",
//     "Lunaris",
//     "Maraith",
//     "Vanwyrm Cryst",
//     "Bushi Noct",
//     "Ragnahawk",
//     "Katress",
//     "Verdash",
//     "Vaelet",
// 	  "Wixen Noct",
//     "Sibelyx",
//     "Elphidran",
//     "Blazehowl",
//     "Blazehowl Noct",
//     "Relaxaurus Lux",
//     "Broncherry Aqua",
//     "Petallia",
//     "Reptyro Cryst",
//     "Kingpaca",
//     "Mammorest Cryst",
//     "Wumpo",
//     "Warsect",
//     "Warsect Terra",
//     "Felbat",
//     "Quivern",
//     "Quivern Botan",
//     "Blazamut",
//     "Helzephyr",
//     "Helzephyr Lux",
//     "Astegon",
//     "Menasting",
//     "Menasting Terra",
//     "Anubis",
//     "Jormuntide",
//     "Suzaku Aqua",
//     "Lyleen",
//     "Faleris",
//     "Faleris Aqua",
//     "Shadowpeak",
//     "Paladius",
//     "Necromus",
//     "Jetragon",
//     "Bellanoir",
//     "Lullu",
//     "Shroomer",
//     "Shroomer Noct",
//     "Kikit",
//     "Prixter",
//     "Yakumo",
//     "Dogen",
//     "Mimog",
//     "Xenovader",
//     "Xenogard",
//     "Silvegis",
//     "Smokie",
//     "Omascul",
//     "Splatterina",
//     "Tarantriss",
//     "Prunelia",
//     "Frostallion",
//     "Nyafia",
//     "Gildane",
//   ];

  //madam data
export const initialData = [
	"Elizabee",
  "Jolthog Cryst",
  "Nox",
  "Mau",
  "Mozzarina",
  "Gobfin Ignis",
  "Hangyu Cryst",
  "Mossanda Lux",
  "Incineram",
  "Leezpunk",
  "Leezpunk Ignis",
  "Gorirat Terra",
  "Grintale",
  "Chillet Ignis",
  "Foxcicle",
  "Pyrin",
  "Pyrin Noct",
  "Kitsun",
  "Lunaris",
  "Dinossom",
  "Maraith",
  "Tombat",
"Vanwyrm Cryst",
  "Bushi Noct",
  "Ragnahawk",
  "Katress",
"Wixen Noct",
  "Verdash",
  "Vaelet",
  "Sibelyx",
  "Elphidran",
"Cryolinx",
"Cryolinx Terra",
  "Blazehowl",
  "Blazehowl Noct",
  "Relaxaurus Lux",
  "Broncherry",
  "Broncherry Aqua",
  "Petallia",
  "Reptyro",
  "Reptyro Cryst",
  "Kingpaca",
  "Mammorest Cryst",
  "Wumpo",
  "Warsect",
  "Warsect Terra",
  "Felbat",
  "Quivern",
  "Quivern Botan",
  "Blazamut",
  "Helzephyr",
  "Helzephyr Lux",
  "Astegon",
  "Menasting",
  "Menasting Terra",
  "Anubis",
  "Jormuntide",
  "Suzaku",
  "Suzaku Aqua",
  "Grizzbolt",
  "Lyleen",
  "Faleris",
  "Faleris Aqua",
"Shadowpeak",
"Paladius",
"Necromus",
  "Orserk",
  "Jetragon",
  "Bellanoir",
  "Lullu",
  "Shroomer",
  "Shroomer Noct",
  "Kikit",
  "Prixter",
  "Yakumo",
  "Dogen",
  "Mimog",
  "Xenovader",
  "Xenogard",
  "Silvegis",
  "Smokie",
"Omascul",
  "Splatterina",
  "Tarantriss",
  "Prunelia",
"Nyafia",
"Gildane",
  "Frostallion"
]