version: "3.9"

services:
  paldex:
    container_name: paldex
    build:
      context: .
      dockerfile: paldex-api
    restart: unless-stopped
    networks:
      - pal_network 

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend-dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - pal_network 
      
networks:
  pal_network:
    driver: bridge
